##This script takes the city-level files generated by Get1940citiesSIS.sas and makes a big 1940 full-year file
##Last updated by Frey May 2017; cosmetic updates 13 July 2017

library(dplyr)
library(dtplyr)
library(data.table)

list.of.files <- list.files(".",pattern="*txt") ##Files with this pattern will be the output from SAS, need to be in 1940/raw/SIS dir

full1940.list <- lapply(list.of.files,fread,select=c("RECTYPE", "YEAR", "DATANUM", "SERIAL", "NUMPREC", "US1940B_0083", 
"US1940B_0084", "CITY", "CITYPOP", "GQ", "GQTYPE", "PAGENO", "HHTYPE", "CNTRY", "STATEFIP", "HEADLOC", "COUNTY", "DWSEQ", 
"STDCITY", "DWELLING", "REEL", "NUMPERHH", "LINE","US1940B_0078", "STREET", "SPLIT", "SPLITHID", "SPLITNUM", "DATANUMP", "SERIALP", 
"PERNUM", "RECTYPEP", "RELATE", "RACE", "MARST", "BPL", "NATIVITY", "CITIZEN", "BPLSTR", "HISTID", "DWSIZE", "OWNERSHP", 
"VALUEH", "FAMSIZE", "NCHILD", "SEX", "AGE", "BIRTHYR", "AGEMARR", "MTONGUE", "EMPSTAT", "LABFORCE", "CLASSWKR", "SEI",
"EDSCOR50","ERSCOR50","EDUC","INCWAGE","IND1950","OCC1950","RENT"),integer64="character") 
##only read vars we need, don't make any bit64s because it's unnecessary

full1940 <- rbindlist(full1940.list) ##convert list to a large data.table
names(full1940) <- tolower(names(full1940)) ##rename vars to lower case the way Stata would

full1940 <- rename(full1940,enumdist=us1940b_0084) ##ugly varname to correct varname
full1940 <- rename(full1940,enumdist_str = us1940b_0083)
full1940 <- rename(full1940,housenum = us1940b_0078)

full1940 <- full1940[!(full1940$statefip=="Illinois" & full1940$county==310) | full1940$city=="Chicago, IL" | full1940$city=="Cicero, IL" | full1940$city=="Evanston, IL" | full1940$city=="Oak Park Village",]
full1940$city[full1940$city=="Oak Park Village"] <- "Oak Park, IL" 
full1940 <- full1940[!(full1940$statefip=="Ohio" & full1940$county==230) | full1940$city=="Springfield, OH",]
full1940 <- full1940[!(full1940$statefip=="Indiana" & full1940$county==1670) | full1940$city=="Terre Haute, IN",]
full1940 <- full1940[!(full1940$statefip=="Massachusetts" & full1940$county==170) | full1940$city=="Somerville, MA"
			| full1940$city=="Cambridge, MA" | full1940$city=="Lowell, MA" | full1940$city=="Newton, MA"
			| full1940$city=="Malden, MA",]
##Toward the bottom of the SAS script, we have to pull some cities that don't have functioning IPUMS IDs using their counties;
##This step ensures we get rid of extraneous cases obtained that way.


fwrite(full1940,"full1940us_update2.txt",sep="|",eol="\r\n") ##write out pipe-delimited
